# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4df751e265157e617592da4e3b2be9fb44e13479ad3ffd018758758129d70b1ae3f01e35d1b45a4a0d1178e44cca91e2e04bb04ba5f9519f451e76f9b4718bde

test:
  secret_key_base: bb25e9e4a5fbd86f6215a6fb2c4bbe8ceaa4aec3f0f801e2fcf4cc2229c8cfc6b7bff4f8408154a9d6a4b77144e59d3e3f4e9b58b545b774c9c07a6bc949dc26

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
